### ISSUE TITLE
PR to crystal std

### ISSUE THREAD

**Issue by bcardiff** [will/hexdump-crystal#1]
This should go to crystal std!

**Comment by asterite** [comment]
@will Would you mind if I include this in the standard library? I think this will be really useful for debugging protocols and inspecting binary data.

**Comment by will** [comment]
Oh, I apparently wasn't watching this project, so didn't see @bcardiff opening this issue. I'll send a pr probably today, no later than tomorrow with tests.

**Comment by asterite** [comment]
Great, thanks! I think the overload with the `buffer` argument should be private.

**Comment by will** [comment]
Yeah, I was mostly trying to follow the to_s, and inspect patterns

**Comment by asterite** [comment]
@will Yes, that would be ideal. However, the `buffer` argument seems to be a pointer. And I'm not sure it can be done with an `IO` since you are placing bytes with a random access to the buffer. Well, maybe it can be done by slicing the current slice in chunks, first dumping the hex data and then the ascii representation.

**Comment by will** [comment]
PR is at https://github.com/crystal-lang/crystal/pull/2547 , closing this
